{
 "title": "K8s Nodes",
 "description": "This is a modern 'Pods View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$cluster $server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=\"$server:9100\", mode!=\"idle\", cluster=\"$cluster\"}[1m])) by (instance, cluster) / sum(rate(node_cpu_seconds_total{instance=\"$server:9100\", cluster=\"$cluster\"}[1m])) by (instance, cluster)) * 100\r\n\r\n",
     "legendFormat": "10.0.10.122"
    }
   ]
  },
  {
   "title": "$cluster $server Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=\"$server:9100\", cluster=\"$cluster\"} * 100 / node_memory_MemTotal_bytes{instance=\"$server:9100\", cluster=\"$cluster\"})\r\n",
     "legendFormat": "10.0.10.122"
    }
   ]
  },
  {
   "title": "$cluster $server Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\r\n  sum(node_filesystem_free_bytes{instance=\"$server:9100\", mountpoint=\"/\", cluster=\"$cluster\"}) / \r\n  sum(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/\", cluster=\"$cluster\"}) * 100\r\n)\r\n",
     "legendFormat": "10.0.10.122"
    }
   ]
  }
 ]
}