persistence:
  enabled: false

adminUser: admin
adminPassword: "${grafanaadminpassword}"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      uid: bdvw8iqhzrm68d
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
      editable: true

dashboardsConfigMaps:
  kubernetes: grafana-dashboards