persistence:
  enabled: false

adminUser: admin
adminPassword: "${grafanaadminpassword}"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


# cd /etc/grafana/datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      uid: bdvw8iqhzrm68d
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
      editable: true

# cd /etc/grafana/provisioning/dashboards --> here you just define the place where the dashboards are located
## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
# take care these configs will create an empty directory called default under /var/lib/grafana/dashboards/ anyway
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: general
        orgId: 1
        folder: ""                # This puts dashboards in the 'General' folder in Grafana UI
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/  # dashboards go directly here
      
      - name: kubernetes
        orgId: 1
        folder: "kubernetes"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes

# Define dashboards to be imported
dashboards:
  general:    
    blackbox-exporter:
      url: https://raw.githubusercontent.com/mohamedsamirspot/Microservices-Infrastructure/refs/heads/test/k8s-tools/monitoring/grafana/dashboards/blackbox-exporter.json
  kubernetes:
    k8s-pods:
      url: https://raw.githubusercontent.com/mohamedsamirspot/Microservices-Infrastructure/refs/heads/test/k8s-tools/monitoring/grafana/dashboards/k8s-pods.json

# cd /var/lib/grafana/plugins --> here you define the plugins to be installed
plugins:
  - grafana-github-datasource