persistence:
  enabled: false

adminUser: admin
adminPassword: "${grafanaadminpassword}"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


# cd /etc/grafana/datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      uid: bdvw8iqhzrm68d
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
      editable: true

# cd /etc/grafana/provisioning/dashboards --> here you just define the place where the dashboards are located
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: kubernetes
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/

dashboards:
  kubernetes:
    k8s-pods:
      url: https://raw.githubusercontent.com/mohamedsamirspot/Microservices-Infrastructure/refs/heads/test/k8s-tools/monitoring/grafana/dashboards/k8s-pods.json
  default:    
    blackbox-exporter:
      url: https://raw.githubusercontent.com/mohamedsamirspot/Microservices-Infrastructure/refs/heads/test/k8s-tools/monitoring/grafana/dashboards/blackbox-exporter.json
