apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-downscaler
    version: v23.2.0
  name: kube-downscaler
  namespace: kube-downscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-downscaler
  template:
    metadata:
      labels:
        application: kube-downscaler
        version: v23.2.0
    spec:
      serviceAccountName: kube-downscaler
      containers:
      - name: downscaler
        image: hjacobs/kube-downscaler:23.2.0
        args:
          # dry run by default, remove to perform downscaling
          # - --dry-run
          # run every minute
          - '--default-downtime=Fri-Fri 05:00-23:59 Africa/Cairo'
          - --interval=60
          - --exclude-namespaces=kube-system,kube-downscaler,karpenter
          - --include-resources=deployments,statefulsets
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: karpenter.sh/nodepool
                    operator: DoesNotExist
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
