apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-contactpoints
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  contactpoints.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: email-mohamed
        receivers:
          - uid: email-mohamed-uid
            type: email
            settings:
              addresses: mohamed.samir.emary@gmail.com
            disableResolveMessage: false
