name: on-pr

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: v0.64.0

      - name: Initialize TFLint plugins
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive --format compact

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: mohamedsamirspot/Microservices-Github-Actions/.github/actions/pre-commit@main
        with:
          python-version: "3.14"
