name: Bump version and tag
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed so the action can push tags

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so the action can see full history/tags

      - name: Bump version
        id: bump
        uses: phips28/gh-action-bump-version@v10.0.0
        with:
          tag-prefix: "v"
          major-wording: 'BREAKING CHANGE,feat!,major'
          minor-wording: 'feat'
          patch-wording: 'fix,perf'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
