name: Bump version
on:
  push:
    branches:
      - main


# Include the token #major, #minor, #patch, or #none somewhere in the commit message of the merge commit or the relevant commit. Example: "feat: rewrite API endpoint to new microservice architecture #major"
# If none of those tokens are found, it falls back to the default bump defined by DEFAULT_BUMP (which defaults to minor
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1.8.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token