name: Terraform Apply

on:
  workflow_dispatch:        # Manual trigger from GitHub UI
    inputs:
      env:
        description: 'Environment to deploy (e.g., dev or prod)'
        required: true
        default: dev

jobs:
  terraform-apply-job:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      env: ${{ github.event.inputs.env }}

    container:
      image: hashicorp/terraform:latest
      options: --entrypoint "/usr/bin/env"
      env:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install AWS CLI inside Terraform container
      - name: Install AWS CLI
        run: |
          apt-get update && apt-get install -y awscli

      # Configure AWS credentials (sets env vars automatically)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: envs/${{ github.event.inputs.env }}
        run: |
          terraform --version
          terraform init


      # ------------------ VALIDATE ------------------
      - name: Terraform Validate
        run: terraform validate
        working-directory: envs/${{ github.event.inputs.env }}

      # ------------------ PLAN ------------------
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: envs/${{ github.event.inputs.env }}

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: envs/${{ github.event.inputs.env }}/tfplan
      # ------------------ APPLY ------------------
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: envs/${{ github.event.inputs.env }}