name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to destroy (e.g., dev or prod)'
        required: true
        default: dev

# This for AWS OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      env: ${{ github.event.inputs.env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------ SETUP ------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # - name: Setup AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::948763340657:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # ------------------ DESTROY ------------------
      - name: Terraform Destroy
        working-directory: envs/${{ github.event.inputs.env }}
        run: |
          if [ -z "$env" ]; then
            echo "❌ ERROR: 'env' variable is not set (expected: dev or prod)"
            exit 1
          fi
          echo "Destroying environment: $env"
          terraform init
          terraform destroy -auto-approve
