name: terraform-apply

on:
  workflow_dispatch:
    inputs:
      account-id:
        description: 'AWS Account ID (e.g., 948763340657)'
        required: true
      region:
        description: 'AWS Region directory (e.g., us-east-1)'
        required: true
      env:
        description: 'Environment directory (e.g., dev | stage | prod)'
        required: true


# This is required for AWS OIDC authentication
permissions:
  id-token: write # It tells GitHub “Yes, this workflow is allowed to request an OIDC token.”
  contents: read # It tells GitHub “Yes, this workflow is allowed to read the repository’s contents.” It is required because actions/checkout@v4 needs read access.


jobs:
  terragrunt-apply:
    name: Terragrunt Apply
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: aws-accounts/${{ github.event.inputs.account-id }}/${{ github.event.inputs.region }}/${{ github.event.inputs.env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      # ------------------ INSTALL TERRAFORM + TERRAGRUNT ------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: latest

      - name: Install Terraform & Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: '0.82.2'
          tf_path: 'terraform'  # This tells Terragrunt to use Terraform binary


      # ------------------ AWS OIDC AUTH ------------------

      # - name: Setup AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ github.event.inputs.region }}

      # Reference: https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ github.event.inputs.account-id }}:role/github-action-role
          aws-region: ${{ github.event.inputs.region }}

      # ------------------ KUBECTL ------------------
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # ------------------ VERIFY TERRAGRUNT DIRECTORY ------------------
      - name: Verify Terragrunt directory exists
        run: |
          echo "Checking path: $WORKING_DIR"
          if [ ! -d "$WORKING_DIR" ]; then
            echo "❌ Directory does not exist: $WORKING_DIR"
            exit 1
          fi
          echo "✔ Found Terragrunt directory"

      # ------------------ TERRAGRUNT INIT ------------------
      - name: Terragrunt Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terragrunt init --all --backend-bootstrap --non-interactive

      # ------------------ TERRAGRUNT VALIDATE ------------------
      - name: Terragrunt Validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terragrunt validate --all

      # ------------------ TERRAGRUNT PLAN ------------------
      - name: Terragrunt Plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terragrunt plan --all

      # ------------------ TERRAGRUNT APPLY ------------------
      - name: Terragrunt Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terragrunt apply --all --auto-approve --non-interactive
