name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy (e.g., dev or prod)'
        required: true
        default: dev

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      env: ${{ github.event.inputs.env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------ SETUP ------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # ------------------ INIT ------------------
      - name: Terraform Init
        working-directory: envs/${{ github.event.inputs.env }}
        run: terraform init

      # ------------------ VALIDATE ------------------
      - name: Terraform Validate
        working-directory: envs/${{ github.event.inputs.env }}
        run: terraform validate

      # ------------------ PLAN ------------------
      - name: Terraform Plan
        id: plan
        working-directory: envs/${{ github.event.inputs.env }}
        run: terraform plan -out=tfplan

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: envs/${{ github.event.inputs.env }}/tfplan

      # ------------------ APPLY ------------------
      - name: Terraform Apply
        working-directory: envs/${{ github.event.inputs.env }}
        run: terraform apply -auto-approve tfplan
